name: Test

on:
  push:
    paths:
      - 'soilprofilecollection/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'soilprofilecollection/**'
      - 'tests/**'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag, or commit SHA to test'
        required: false
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "without optional extras"
            install-extras: ""
          - name: "with plot extra"
            install-extras: "-E plot"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ matrix.install-extras }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies ${{ matrix.name }}
        run: poetry install --no-interaction --no-root ${{ matrix.install-extras }}
      - name: Run tests
        run: poetry run pytest
